### ISSUE TITLE
[Q] schema parsing

### ISSUE THREAD

**Issue by bademux** [raml-org/raml-java-parser#104]
Hi,
Is it work?
Thanks

**Comment by svacas** [comment]
yes, it should, for json schema and xsd

**Comment by bademux** [comment]
ok, looks like iI hit https://github.com/raml-org/raml-java-parser/commit/e71ccf9cbba451152c2eb109e8ba00de3f2b8726

**Comment by bademux** [comment]
Is there possibility to inject own Resource loaders\hook existing.
It is critical to control the way resource are fetched (eg. fetching with auth).
The swagger way is to do all the stuff inside "parser" it leads to monstrous dependency and unobvious usage.

My proposal is to add api for adding resolvers implementing the api.
Existing [ResourceLoader](https://github.com/raml-org/raml-java-parser/blob/master/src/main/java/org/raml/parser/loader/ResourceLoader.java) is not sufficient for public API. 
There should be separate method to test if Loader can handle URI.
InputStream as return type is _error prone_. Who will have responsibility to close the stream?

It seams that in existing code Streams are never closed, please validate my observation.

**Comment by bademux** [comment]
But back to the subj.
@svacas json schema isn't parsed [SchemaTupleBuilder](https://github.com/raml-org/raml-java-parser/blob/master/src/main/java/org/raml/parser/builder/SchemaTupleBuilder.java#L62)

**Comment by bademux** [comment]
@svacas @yyamano Please release fixed version for https://github.com/raml-org/raml-java-parser/commit/e71ccf9cbba451152c2eb109e8ba00de3f2b8726 
It is real pain in the ass.

**Comment by eleonoraortega** [comment]
Closing as per the fix is included in 0.8.14
