### ISSUE TITLE
Wron assumption for schema detect

### ISSUE THREAD

**Issue by bademux** [raml-org/raml-java-parser#105]
There is error prone assumption in the [SchemaTupleBuilder](https://github.com/raml-org/raml-java-parser/blob/master/src/main/java/org/raml/parser/builder/SchemaTupleBuilder.java#L62).
Parser tries to guess schema type by mime. It isn't so good idea as it looks as someone could use  _application/x-***_ mime. It is absolutely compliant with RFC. Another reason is legacy _text/html_ mime for json...

I'm afraid the only way is to check first char of file (please be aware of [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) )

**Comment by svacas** [comment]
The raml spec does not cover how to infer the schema types, and as you could use your own custom schema format (though the parser won't validate in that case) checking the first char of the schema may not be right.
