### ISSUE TITLE
'examples' does not seem to work in v2

### ISSUE THREAD

**Issue by scottcarey** [raml-org/raml-java-parser#108]
The following works in API workbench (though seems quirky? is the 1.0 spec solid here?), but fails in the v2 alpha parser.  It is not noted as missing in the MISSING document.

````yaml
#%RAML 1.0
title: Simple API
version: v1
baseUri: http://foobar.com/simple/{version}
types:
  Stuff:
    type: object
    properties:
      id: string
      stuff?: string
    examples:
      abc:
        description: abc example
        content:
          id: abc
          stuff: axe bearing cow
      xyz:
        description: xyz example
        content:
          id: xyz
          stuff: xylophone yelping zebra
/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Stuff
      404:
````

result:

````
2 errors found:

	- Invalid type Object, expected Object [line=13, col=9]

	- Invalid type Object, expected Object [line=18, col=9]
````

The 1.0 spec is devoid of any example using  'examples' as well.

I can use a single example to remove the error:

````yaml
    example:
      id: abc
      stuff: axe bearing cow
````

**Comment by sichvoge** [comment]
@scottcarey, the syntax you are using is RC1. You would need to change `content` to `value`. The Workbench is currently on RC1, but there is an alpha support for RC2/GA [here](https://github.com/mulesoft/api-workbench/releases/tag/v0.8.29). 

The v2 version of the Java parser is based on RC2/GA already.

**Comment by scottcarey** [comment]
Yes, the error message is almost worthless, and the workbench's auto-complete led me astray.


However, changing `content` to `value` doesn't help anyway.

````
#%RAML 1.0
title: Simple API
version: v1
baseUri: http://foobar.com/simple/{version}
types:
  Stuff:
    type: object
    properties:
      id: string
      stuff?: string
    examples:
      abc:
        description: abc example
        value:
          id: abc
          stuff: axe bearing cow
      xyz:
        value:
          id: xyz
          stuff: xylophone yelping zebra
/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Stuff
````

yields the following errors from validation:

````
[Invalid type Object, expected Object [line=13, col=9], Invalid type Object, expected Object [line=18, col=9]]
````

the below works without validation errors:

````
#%RAML 1.0
title: Simple API
version: v1
baseUri: http://foobar.com/simple/{version}
types:
  Stuff:
    type: object
    properties:
      id: string
      stuff?: string
    examples:
      abc:
        id: abc
        stuff: axe bearing cow
      xyz:
        id: xyz
        stuff: xylophone yelping zebra
/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Stuff
````

However, the example names do not work.   I can extract the `examples()` list from the type, and see the `value()`, but `name()` is null (I expect `abc` and `xyz`, but maybe that is not right).

**Comment by scottcarey** [comment]
As a test case for this, I suggest the following four variants (assuming the below is valid, which it would appear to be based on the latest v2 spec):

````
#%RAML 1.0
title: Simple API
version: v1
baseUri: http://foobar.com/simple/{version}
types:
  Stuff:
    type: object
    properties:
      id: string
      stuff?: string
    examples:
      abc:
        id: abc
        stuff: axe bearing cow
      xyz:
        value:
          id: xyz
          stuff: xylophone yelping zebra
      ijk:
        description: example with stuff
        value:
          id: ijk
          stuff: intrigued jumping koala
      qrs:
        description: example without stuff
        value:
          id: qrs
/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Stuff
````

**Comment by svacas** [comment]
As you already found out nesting an example within `value` is not yet supported (it's in the MISSING list under `Type system gaps`).
The issue with `name` should have been fixed by 4b00f2897ce23f790c319a4b99c2c923c4dd4d5f

**Comment by scottcarey** [comment]
I'll pull the latest and try again to verify the `name()` fix

**Comment by scottcarey** [comment]
yup, name() works.  That is what I get for being ~ 24 hours behind :)

If the lack of 'value' support in examples is in the MISSING doc, then this issue can be closed from my perspective.
