### ISSUE TITLE
How to access protected raml file

### ISSUE THREAD

**Issue by ymohdriz** [raml-org/raml-java-parser#113]
Hi team,

How to access protected raml file using raml parser?

In swagger, they expect an authorizationValue.
Is raml provided any solution to access protected source?

**Comment by svacas** [comment]
There's nothing defined for that. Though if it's useful we may add it.

**Comment by ymohdriz** [comment]
It will be really useful as API providers would like to protect their
resources even the raml source file.. Thanks

**Comment by svacas** [comment]
In the meantime you can implement a custom `ResourceLoader` that adds the required headers and pass it to the builder.
