### ISSUE TITLE
Empty traits are considered invalid

### ISSUE THREAD

**Issue by moliva** [raml-org/raml-java-parser#166]
In this case, the parser returns a `Invalid root node SyNullNode. Expected : Mapping.` error when applying the empty trait.
```raml
#%RAML 1.0
title: Files API
traits:
  hello:
resourceTypes:
   file:
     get:
       is: [hello]
/files:
  type: file
```

**Comment by eleonoraortega** [comment]
Duplicated with https://github.com/raml-org/raml-java-parser/issues/127
