### ISSUE TITLE
Deployment on maven central repository

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#24]
It would make usage easier when one does not need to include the mulesoft repository in the pom.

**Comment by balthorium** [comment]
What is the id and url of the mulesoft maven repository, and artifactId of the raml-java-parser?

**Comment by ddossot** [comment]
This should answer both your questions: https://repository.mulesoft.org/nexus/content/repositories/public/org/raml/raml-parser/0.8.9/raml-parser-0.8.9.pom

**Comment by balthorium** [comment]
Thanks!

**Comment by ajbrown** [comment]
For Gradle:

    maven { url 'https://repository.mulesoft.org/nexus/content/groups/public' }

**Comment by rrinaudo** [comment]
We are working on uploading the parser into Maven central under org.raml ... Will keep you posted once it's done. 

Until then, use the repository David Dossot pointed out.

**Comment by rrinaudo** [comment]
We already uploaded the binaries to Maven Central

https://repo1.maven.org/maven2/org/raml/raml-parser/

Cheers

**Comment by nidi3** [comment]
but 0.8.12 is missing

**Comment by rrinaudo** [comment]
Uploading 0.8.12 today, will update once it's there

**Comment by olensmar** [comment]
oh - awesome - I'll wait for that any build a new version of the plugin

**Comment by rrinaudo** [comment]
Done, it's there https://repo1.maven.org/maven2/org/raml/raml-parser/0.8.12/

**Comment by lanwen** [comment]
duplicates #59
