### ISSUE TITLE
Make type validation a public API

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#259]
ExampleValidationPhase validates example values against their types.
It'd be useful if this function would be publicly available. So that it can be validated if a given value is valid for a given type.
A first step could be to make the document Node of an API available, so one could use
`ExampleValidationPhase.validate(TypeDeclarationNode type, String exampleValue)`

**Comment by svacas** [comment]
check [TypeDeclaration.validate()](https://github.com/raml-org/raml-java-parser/blob/master/raml-parser-2/src/main/java/org/raml/v2/api/model/v10/datamodel/TypeDeclaration.java#L90)

**Comment by nidi3** [comment]
Sorry, I was blind, that's exactly what I searched.
