### ISSUE TITLE
String type validation is too restrictive

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#261]
`StringTypeDeclaration.validate("sss")` is ok
`StringTypeDeclaration.validate("1")` yields `Invalid type Integer, expected String`
`StringTypeDeclaration.validate("{}")` yields `Error validating JSON. Error: - Invalid type Object, expected String`

All 3 values are strings and should not produce errors.

**Comment by svacas** [comment]
the thing is the validation method needs to support xml, json and yaml, we could force string validation using quotes: 

`StringTypeDeclaration.validate("\"1\"")`

right now that works for numbers but not for `{}`

**Comment by nidi3** [comment]
I see. The validation depends on the serialization form (JSON, XML, yaml, web form, header/query param/uri param)
So the clean solution would be to add this to the API: 
`List<ValidationResult> validate(SerializationForm form, String payload)` 
right?

**Comment by nidi3** [comment]
Maybe one more serialization form is needed to validate the `example` section
