### ISSUE TITLE
Encoding detection does not detect ISO-8859-15 and is not overridable

### ISSUE THREAD

**Issue by boillodmanuel** [raml-org/raml-java-parser#271]
Hello,

ISO-8859-15 encoding adds the € symbol. If the RAML file is encoded in ISO-8859-15, the RAML Parser fails to import it properly.

It seems that juniversalchardet doesn't detect this encoding.
And we cannot override the RAML parser behaviour to set the encoding or to change the encoding detection library (especially, with multi files RAML).

It would be great to support that somehow.

**Comment by svacas** [comment]
hi,
though the parser may support includes with some encodings other than UNICODE, it's only guaranteed to work with UNICODE.
RAML is based on YAML that (like JSON) only supports [UNICODE](http://yaml.org/spec/1.2/spec.html#id2771184).
