### ISSUE TITLE
RamlModelBuilder does not fully support files with Byte Order Mark (BOM)

### ISSUE THREAD

**Issue by constint** [raml-org/raml-java-parser#305]
### Whey providing a Reader, the BOM is not supported
The method ` RamlModelResult buildApi(Reader reader, String ramlLocation)`
uses `IOUtils.toString` under the hood to get the content string.
This keeps the BOM intact, which leads to an "Invalid header" exception down the line.

### Whey providing a location, the BOM is supported
The method `RamlModelResult buildApi(String ramlLocation)` uses
`StreamUtils.toString` which strips the BOM before returning the content : 

```java  
String encoding = detectEncoding(content);
return new String(trimBom(content), encoding);
```

**Comment by svacas** [comment]
If you create the reader with the right encoding the BOM shouldn't be an issue even using `IOUtils.toString()`
