### ISSUE TITLE
URI parameters are not extracted if not formally defined

### ISSUE THREAD

**Issue by npayneau** [raml-org/raml-java-parser#312]
Hello,

**Parser: raml-java-parser2**

Use case:

```
  /users:
    get:
      description: get users
      responses:
        200:
          body:
            application/json:
  /users/{user_id}:
    description:
    get:
      description: one user
      responses:
        200:
```

With example.raml, the following is parsed with a /users/{user_id} resource that has with an empty uriParameters():

According to the spec:

> If a URI parameter in a resource's relative URI is not explicitly described in a uriParameters property for that resource, it MUST still be treated as a URI parameter with defaults as specified in the Named Parameters section of this specification. Its type is "string", it is required, and its displayName is its name (i.e. without the surrounding curly brackets [{] and [}]).

So I'm expecting that uriParameters() will return the inferred URI parameter definition using the specified default values.

**Comment by shumy** [comment]
Please fix this bug.

**Comment by giordanolucas** [comment]
This issue still needs to be fixed

**Comment by pacafuentes** [comment]
Fixed
