### ISSUE TITLE
type boolean is not case sensitive

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#323]
`True`  and `TRUE` are trated as valid booleans. They should not in my opinion.

**Comment by machaval** [comment]
But we are yaml compliant so valid booleans are http://yaml.org/type/bool.html

**Comment by nidi3** [comment]
But the spec talks about "JSON boolean"

**Comment by nidi3** [comment]
And `yes` is not accepted, but it should according to yaml
