### ISSUE TITLE
log4j warnings

### ISSUE THREAD

**Issue by phonyphonecall** [raml-org/raml-java-parser#33]
When using the parser as a maven dependency for a maven plugin I get the following warnings in logs:

```
log4j:WARN No appenders could be found for logger (org.apache.commons.beanutils.PropertyUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

I am not sure if there is a clean way to resolve this issue if the parser is used as a plugin. I am also no expert on log4j, and could be wrong.

**Comment by ddidier** [comment]
@phonyphonecall Hi, have you resolved this issue because I can't make it working wherever I put my log4j.propertise? Thanks

**Comment by djarnis73** [comment]
I ran into the same problem, I sprinkled log4.properties all over my project to no avail. Then I tried running maven like:

`mvn raml:generate -Dlog4j.configuration=file://(absolute path to project)/raml/log4j.properties`

That did silence the warning, my final solution was to add the following plugin to my pom.xml:
```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>properties-maven-plugin</artifactId>
	<version>1.0.0</version>
	<executions>
		<execution>
			<goals>
				<goal>set-system-properties</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<properties>
			<property>
				<name>log4j.configurationx</name>
				<value>${project.baseUri}raml/log4j.properties</value>
			</property>
		</properties>
	</configuration>
</plugin>
```
Ugly as hell, but I prefer it to the noise in the build log. I'm sure there is a simpler solution but I have not yet has any luck finding the right words to google for.
