### ISSUE TITLE
Parsing fail when resource type is an array

### ISSUE THREAD

**Issue by boillodmanuel** [raml-org/raml-java-parser#340]
With following RAML 1.0:

```
#%RAML 1.0
title: API
version: v1
resourceTypes:
  type1:
    get:
      responses:
        200:
          description: ok (from resource type "type 1")
/users:
  type: [type1]
  get:
    description: "GET users"
```

parser fails with following error: `Invalid element Array[type1].`

the content seems to be valid on API Designer

**Comment by svacas** [comment]
you can only inherit from a single resource type, so arrays are not supported
