### ISSUE TITLE
Parser accepts invalid values under 'multipleOf' facets

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-java-parser#344]
According to the RAML 1.0 spec, the definition of **multipleOf** facet for Number and Integer types is:

> A numeric instance is valid against multipleOf if the result of dividing the instance by this keyword's value is an integer.

That means that the value of **multipleOf** is the Divisor of the division, but the parser accepts 0 as a value, which is wrong.

Parser MUST only accept values greater than zero.

**Comment by sichvoge** [comment]
I think that's not really correct. The definition of `multipleOf` should strictly follow the same restrictions from JSON schema. As you see [here](https://spacetelescope.github.io/understanding-json-schema/reference/numeric.html#multiples) `multiple: 0` is very much allowed.

Is that something we would need to clarify in the spec a bit more?

**Comment by sichvoge** [comment]
I think the spec is not very clear about that fact, but I agree that it should be greater than zero.
