### ISSUE TITLE
Custom error messages for pattern validation

### ISSUE THREAD

**Issue by mbaluda** [raml-org/raml-java-parser#360]
Type definitions in RAML do not support the error facet for customizing error messages on insuccessful validation. The raml-js-parser supports the attached solution.
[patterns.txt](https://github.com/raml-org/raml-java-parser/files/909882/patterns.txt)

**Comment by svacas** [comment]
AFAIK when you use `value` inside pattern the only extra keys you can define are annotations.
So the key `error` shouldn't be allowed.

**Comment by svacas** [comment]
let me know if you find anything in the spec related to this and reopen the issue
