### ISSUE TITLE
regex format for string patterns

### ISSUE THREAD

**Issue by mbaluda** [raml-org/raml-java-parser#361]
Does the RAML standard define which regex language should be used for string patterns in type definitions?
The raml-java-parser and raml-js-parser projects do not support the same language for example with respect to unicode categories
http://www.regular-expressions.info/unicode.html

**Comment by sichvoge** [comment]
That should help https://github.com/raml-org/raml-spec/issues/577.

**Comment by mbaluda** [comment]
In this case, the raml-org/raml-java-parser implementation is not aligned with the specification

**Comment by sichvoge** [comment]
Thanks @mbaluda for raising it. I will check with the team.

**Comment by sichvoge** [comment]
You have a quick example?

**Comment by mbaluda** [comment]
The example could be the regex "^[\p{L}]*$" that match strings of letters of any alphabet.
However, the spec does not prevent the implementation to support unicode categories, it just recommend schema authors not to use them in a specification:
"" 
schema authors SHOULD limit themselves to the following regular expression tokens: 
...
""

So I guess there is nothing wrong with the implementation
