### ISSUE TITLE
car i use raml java parser to read raml files to do validaiton?

### ISSUE THREAD

**Issue by kiwiwin** [raml-org/raml-java-parser#384]
Hi, 

i have used raml for a while, and saw this great project. i am thinking that is it available that if i have full documented my api in raml, and when a request is coming from one specific api, i can read the raml files to validate is that request satisify the validation rule?

thank you in advance

**Comment by aamura** [comment]
Hi, sure !!!. Basically you have to do this:

RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(input);
if (ramlModelResult.hasErrors())
{
    for (ValidationResult validationResult : ramlModelResult.getValidationResults())
    {
        System.out.println(validationResult.getMessage());
    }
}
else
{
    Api api = ramlModelResult.getApiV10();
}

Please, take a look at raml-java-parser/README.md file for more information.
