### ISSUE TITLE
`Uses` is forbidden in !included DataType fragments

### ISSUE THREAD

**Issue by fractaloop** [raml-org/raml-java-parser#405]
raml-java-parser will not allow `uses` inside a DataType fragment if it's included by another file.

The RAML 1.0 spec does indicate that `uses` is allowed in typed fragments, and raml-java-parser will allow them if they are loaded directly, but raises a validation error if the DataType fragment is !included.

I've created [a failing test case on my fork](https://github.com/fractaloop/raml-java-parser/commit/0583d3c70002131995501b8d0ca0ae7483ec046b). The "output.txt" is wrong (I'm not sure what it _should_ be), but it clearly includes an ErrorNode.

I tried to trace this down for a PR, but I haven't been able to understand what causes this behavior.

**Comment by fractaloop** [comment]
After tracing through the phases, it appears that the `RamlFragmentGrammarTransformer` converts the `RamlTypedFragmentNode` to a `TypeDeclarationNode` using the factory from the DataType rules.

**Comment by pacafuentes** [comment]
Hi, sorry for the delay.

Check this commit https://github.com/raml-org/raml-java-parser/commit/ac5b433ae644614ba2a74466886b52b92f71e097 which fixes the issue.

And this commit https://github.com/raml-org/raml-java-parser/commit/5d64094667b774f04f901ec7a9f066ef16df3bdc which fixes a NPE created by the original fix.
