### ISSUE TITLE
!include not properly resolved when passed as a template variable

### ISSUE THREAD

**Issue by pmbober** [raml-org/raml-java-parser#48]
Please take a look at the last commit on this branch.  It contains a test case that demonstrates what I think is a bug in the includes resolver.  

https://github.com/pmbober/raml-java-parser/tree/pmbober/resource-type-example-include-bug

In short, I define a resource type which has an example whose value is passed from the actual type definition.  If value passed in is a !include, the example resolves to the name of the include file instead of its contents.

It works, however, if I pass the file name and apply the !include in the template definition.  But, this is not what I want to do since I want the ability to pass hard-coded values as well as file references.

**Comment by olensmar** [comment]
I can confirm - have had the same issue with the parser

**Comment by olensmar** [comment]
any update on this? we have users of the RAML plugin for Ready! API that bump into this...
