### ISSUE TITLE
Raml parser (version 0.8) is vulnerable to XML External Entity Injections

### ISSUE THREAD

**Issue by ymohdriz** [raml-org/raml-java-parser#481]
Hi team,

An XML External Entity Injection occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

Attached the raml file and parsing the attached raml is vulnerable to XML external injections.

How to disallow doctype (http://apache.org/xml/features/disallow-doctype-decl) in xml parser used by raml parser?
[api1.txt](https://github.com/raml-org/raml-java-parser/files/1871678/api1.txt)

Thanks,
Mohammed

Aha! Link: https://mulesoft-roadmap.aha.io/features/APIRAML-65

**Comment by ymohdriz** [comment]
Hi team,

Any updates on this issue?

Thanks,
Mohammed

**Comment by jstoiko** [comment]
Fixed in [0.8.34](https://github.com/raml-org/raml-java-parser/releases/tag/0.8.34).

**Comment by ymohdriz** [comment]
Hi @jstoiko,

Thanks for the update. 
Maven repo contains 0.8.29 version.
When will the latest version 0.8.34 available in maven?

Thanks,
Mohammed
