### ISSUE TITLE
Generated JSON schema does not support ENUM

### ISSUE THREAD

**Issue by hu3b1129** [raml-org/raml-java-parser#497]
RAML ENUM types seems not to be supported in the JSON schema.
Assuming to have the RAML type definition

  myEnumType:
    type:
      enum: [
        ENUM1,
        ENUM2
        ]

The generated JSON schema is empty:

  {"type":"string","definitions":{},"$schema":"http://json-schema.org/draft-04/schema#"}

however the XML schema covers enumerations properly. 
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://validationnamespace.raml.org" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://validationnamespace.raml.org">
    <element name="myEnumType">
        <simpleType>
            <restriction base="string">
                <enumeration value="ENUM1"/>
                <enumeration value="ENUM2"/>
            </restriction>
        </simpleType>
    </element>
</schema>

What am I doing wrong?

**Comment by jpbelang** [comment]
You were doing nothing wrong.  There was no code.
