### ISSUE TITLE
Upgrade to snakeyaml 1.14 please

### ISSUE THREAD

**Issue by inthemill** [raml-org/raml-java-parser#54]
Can you please upgrade to snakeyaml 1.14 or make raml-java-parser compatible with snakeyaml 1.14, as this is the latest stable release.

The latest Spring boot depends on snakeyaml 1.14, and i have to exclude it to be able to work with raml

**Comment by jdfolino** [comment]
Facing a similar issue. Seems as though:

org.yaml.snakeyaml.nodes.Tag has removed the following constant which the RAML parser is dependant on

public static final Tag YAML
