### ISSUE TITLE
Upload Maven Snapshots and Releases to OSS Sonatype

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-java-parser#59]
Any plans to upload Snapshots and Releases to https://oss.sonatype.org or Maven Central

http://central.sonatype.org/pages/ossrh-guide.html.

**Comment by petrochenko-pavel-a** [comment]
It is required to get ramp-for-jaxrs playing well with central only

**Comment by ddossot** [comment]
Having release candidates of the 0.9 parser would be great too because, currently, RAML for JAX-RS depends on a snapshot, if in its released versions, which is super fragile.

**Comment by petrochenko-pavel-a** [comment]
yep. :-) +1:

**Comment by ddossot** [comment]
Any progress on this?

**Comment by svacas** [comment]
I'm gathering the requirements from Sonatype to publish to central through them, I'll keep you posted.

**Comment by canoasan** [comment]
Done.
https://oss.sonatype.org/#nexus-search;gav~org.raml~raml-parser~~~~kw,versionexpand

**Comment by ddossot** [comment]
It's not in central yet: I reckon the latest release needs to be promoted?

**Comment by canoasan** [comment]
You can take a look now. http://search.maven.org/#search%7Cga%7C1%7Craml-parser

**Comment by jageay** [comment]
Any reason for version 0.8.12 not being available in Central nor in Sonatype OSSRH?

**Comment by markdingram** [comment]
A bump to try and get 0.8.12 pushed to Central

**Comment by rrinaudo** [comment]
We are uploading 0.8.12 today. Will update once it's there.

**Comment by rrinaudo** [comment]
It's there now. 
https://repo1.maven.org/maven2/org/raml/raml-parser/0.8.12/

**Comment by markdingram** [comment]
great!

**Comment by lanwen** [comment]
Please upload **0.8.13** to central

**Comment by haroldcarr** [comment]
I just checked central and 0.8.12 is the latest.  I need the `displayName` fix that is in 0.8.13.  Please push.

**Comment by ddossot** [comment]
It would be nice if releases could be systematically pushed to central instead of having us begging for it every time :crying_cat_face:

**Comment by svacas** [comment]
0.8.13 is published to central, and the publishing is now part of the release procedure
