### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by hwellmann** [raml-org/raml-java-parser#617]
Can you please (re-)publish artifacts to Maven Central? I see there's a 1.0.33 tag now, but Maven Central is still at 1.0.28.

Aha! Link: https://mulesoft-roadmap.aha.io/features/APIRAML-40

**Comment by jpbelang** [comment]
They are currently pushed to the mulesoft repository.  This version of the parser is being deprecated in favor of the AMF parser.

**Comment by jpbelang** [comment]
Central now has artifacts.
