### ISSUE TITLE
date-only & datetime-only allow one digit months and days

### ISSUE THREAD

**Issue by JuanAller** [raml-org/raml-java-parser#652]
```yaml
/test:
  get:
    queryParameters:
      dateOfJoining:
        required: false
        type: date-only (or datetime-only)
        example: 2013-3-2
    responses:
      200:
        body:
          application/json:
```
date-only example value 2013-3-2 is valid
datetime-only example value 2013-3-2T03:03:04 is valid 
https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14

**Comment by jpbelang** [comment]
The correct PR is at https://github.com/raml-org/raml-java-parser/pull/655 (I was having trouble with a bad local commit.

The work is done for rfc 3339.  That said, it could have some consequence for existing specs, ad previously seen as correct ramls will now be seen as incorrect.  This change also breaks Postel's law (the robustness principle, for reference: https://en.wikipedia.org/wiki/Robustness_principle)

Could you check around your area to see if this is ok ?

**Comment by jpbelang** [comment]
I've also updated the comment you wrote, could you check that this is what you meant ?  (Pretty sure it is :-) )

**Comment by JuanAller** [comment]
You are right, it could have some consequences for existing specs, can you make this configurable ? using system properties (https://github.com/raml-org/raml-java-parser/blob/master/yagi/src/main/java/org/raml/yagi/framework/util/DateUtils.java#L29) one property for months and another for days

**Comment by JuanAller** [comment]
single digit is getting allowed for hours, minutes and seconds as well (h:m:s) e.g. 2013-3-1T2:3:1 is showing valid format.
