### ISSUE TITLE
ContextPath is not working on windows ending in invalid paths.

### ISSUE THREAD

**Issue by juandesi** [raml-org/raml-java-parser#661]
See this line here, it's searching for `/` but in windows systems should check for `\`.

https://github.com/raml-org/raml-java-parser/blob/166fd515153a1b7688d7c049221ced220410f3aa/src/main/java/org/raml/parser/tagresolver/ContextPath.java#L106

Using `Paths.get()` is a possible solution OR File.separator

**Comment by jpbelang** [comment]
Could you check that this works ?  I don't have access to windows machines.

Closing, but don't be shy to reopen.
