### ISSUE TITLE
org.raml.v2.internal.impl.commons.nodes.StringTemplateNode cannot be cast to org.raml.yagi.framework.nodes.ReferenceNode

### ISSUE THREAD

**Issue by JuanAller** [raml-org/raml-java-parser#664]

**Comment by JuanAller** [comment]
![raml-parser-stacktrace](https://user-images.githubusercontent.com/12023344/66584625-ddf6c880-eb5b-11e9-93a5-9a2ec44a7da6.png)

**Comment by jpbelang** [comment]
The error might not be ideal, but the spec is wrong.  There is no definition got Get<<itemType>>.
Are you complaining about the error ?  Because that's what I'm fixing :-)
