### ISSUE TITLE
org.raml.model.Action lacks 'displayName' field

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-java-parser#67]
Hi, guys

The `org.raml.model.Action` lacks `displayName`, but according to Spec 0.8 it should.
May it be me looking on the wrong version?

Regards,
Konstantin

**Comment by sumveds** [comment]
When are we adding ```displayName``` property in ```org.raml.model.Action```? Any closure date you guys have decided?

**Comment by lrevnic** [comment]
Hi,

Any updates on this thread?

Thank you,
Lucian

**Comment by eleonoraortega** [comment]
Closing as currently version0.8.17 includes this fix already.

**Comment by sichvoge** [comment]
@eleonoraortega I think that that's not correct! The specification does not imply that there is a `displayName` on HTTP verbs.
