### ISSUE TITLE
Strings "true" and "false" are valid for boolean type

### ISSUE THREAD

**Issue by JuanAller** [raml-org/raml-java-parser#678]
`#%RAML 1.0
title: Sample API
types:
  TestType:
    type: object
    properties:
      count?: integer
      flag?: boolean
      name?: string
/test:
  post:
    body: 
      application/json: 
        type: TestType
        example: |
          {
            "count": 12,
            "flag": "false",
            "name": "Joe"
          }`
field "flag" is boolean type, but example value is "false"

**Comment by eduardo-rubio** [comment]
AMF fails also with strings "true" and "false".
@jpbelang @jstoiko This issue should be solve using a property to prevent backward compatibility issues.

**Comment by jpbelang** [comment]
The org.raml.strict_booleans property was added to solve this issue.
