### ISSUE TITLE
Error when parsing JSON schemas

### ISSUE THREAD

**Issue by ok11** [raml-org/raml-java-parser#68]
Parsing the following JSON schema as a part of a RAML definition, produces the error:

> -1 invalid JSON schema (image): Unexpected character ('i' (code 105)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

This is strange, because the schema validation by diverse JSON schema validators works just fine (http://jsonschemalint.com/, https://github.com/fge/json-schema-validator,...). And, also as in my other ticket, forwarded here by Konstantin from the RAML for JAX-RS team, the output is absolutely insufficient to find the root cause.

The schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "required": ["id", "location"],
  "properties": {
    "id": {
      "description": "The ID of the image",
      "type": "string"
    },
    "location": {
      "description": "Location of the image",
      "type": "string"
    }
  }
}
```

**Comment by ok11** [comment]
Got that to work, the issue was in the RAML file, not in the JSON schema. So, closing the issue. But still it makes sense to spend some effort working on error diagnostics, currently it is completely misleading :/

**Comment by ddossot** [comment]
Do you mind detailing what was the issue in RAML which triggered this misleading error?

**Comment by ok11** [comment]
Sure, if it helps.
The issue was that I referenced the json schemas as I do for traits, i.e. without the name part.
That is, it was like

```yaml
schemas:
  - !include schema-image.json
  - !include schema-images-list.json
```

The exception disappeared when I changed that to

```yaml
schemas:
  - image: !include schema-image.json
  - images: !include schema-images-list.json
```

Reading the error message directly I assume that the error is in the JSON schema itself. And this is obviously  not the case.
