### ISSUE TITLE
Add support for CONNECT method

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-java-parser#95]
The current supported methods are:
GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS, TRACE

the parser should also support CONNECT

**Comment by usarid** [comment]
No, RAML 1.0 does not support TRACE or CONNECT, and I see no need for the
RAML 0.8 parser to support them either, honestly, but I don't feel strongly
about that one.

**Comment by svacas** [comment]
Then 0.8 parser will support TRACE and CONNECT for consistency with other implementations, and 1.0 will not.

**Comment by usarid** [comment]
That's fine if we need the 0.8 one to support those -- do we?

**Comment by svacas** [comment]
IMO the best solution would be clarifying in the 0.8 spec the explicit list of methods that must be supported

**Comment by usarid** [comment]
We did make it explicit that the method must be one listed in the two RFCs, which include TRACE and CONNECT. So RAML 0.8 allows them. Whether an implementation must support them - technically the reference implementation should, but if ours doesn't I would not feel too bad, as it's hard to argue it has a good use in the RAML context.





On Wed, Feb 17, 2016 at 6:50 AM -0800, "svacas" <notifications@github.com> wrote:












IMO the best solution would be clarifying in the 0.8 spec the explicit list of methods that must be supported
